/**
 * API Endpoints Registry
 * File: endpoints.js
 */

import { API_BASE_URL, API_VERSION } from '@config/env';

const normalizeBaseUrl = (value) => String(value || '').replace(/\/+$/, '');
const baseUrl = `${normalizeBaseUrl(API_BASE_URL)}/api/${API_VERSION}`;

export const endpoints = {
  AUTH: {
    LOGIN: `${baseUrl}/auth/login`,
    REGISTER: `${baseUrl}/auth/register`,
    REFRESH: `${baseUrl}/auth/refresh`,
    LOGOUT: `${baseUrl}/auth/logout`,
    ME: `${baseUrl}/auth/me`,
    FORGOT_PASSWORD: `${baseUrl}/auth/forgot-password`,
    RESET_PASSWORD: `${baseUrl}/auth/reset-password`,
    CHANGE_PASSWORD: `${baseUrl}/auth/change-password`,
    VERIFY_EMAIL: `${baseUrl}/auth/verify-email`,
    VERIFY_PHONE: `${baseUrl}/auth/verify-phone`,
    RESEND_VERIFICATION: `${baseUrl}/auth/resend-verification`,
    MFA_VERIFY: `${baseUrl}/auth/mfa/verify`,
    MFA_RESEND: `${baseUrl}/auth/mfa/resend`,
  },
  USER_SESSIONS: {
    LIST: `${baseUrl}/user-sessions`,
    GET: (id) => `${baseUrl}/user-sessions/${id}`,
    DELETE: (id) => `${baseUrl}/user-sessions/${id}`,
  },
  TENANTS: {
    LIST: `${baseUrl}/tenants`,
    CREATE: `${baseUrl}/tenants`,
    GET: (id) => `${baseUrl}/tenants/${id}`,
    UPDATE: (id) => `${baseUrl}/tenants/${id}`,
    DELETE: (id) => `${baseUrl}/tenants/${id}`,
  },
  FACILITIES: {
    LIST: `${baseUrl}/facilities`,
    CREATE: `${baseUrl}/facilities`,
    GET: (id) => `${baseUrl}/facilities/${id}`,
    UPDATE: (id) => `${baseUrl}/facilities/${id}`,
    DELETE: (id) => `${baseUrl}/facilities/${id}`,
    GET_BRANCHES: (id) => `${baseUrl}/facilities/${id}/branches`,
  },
  BRANCHES: {
    LIST: `${baseUrl}/branches`,
    CREATE: `${baseUrl}/branches`,
    GET: (id) => `${baseUrl}/branches/${id}`,
    UPDATE: (id) => `${baseUrl}/branches/${id}`,
    DELETE: (id) => `${baseUrl}/branches/${id}`,
  },
  DEPARTMENTS: {
    LIST: `${baseUrl}/departments`,
    CREATE: `${baseUrl}/departments`,
    GET: (id) => `${baseUrl}/departments/${id}`,
    UPDATE: (id) => `${baseUrl}/departments/${id}`,
    DELETE: (id) => `${baseUrl}/departments/${id}`,
    GET_UNITS: (id) => `${baseUrl}/departments/${id}/units`,
  },
  UNITS: {
    LIST: `${baseUrl}/units`,
    CREATE: `${baseUrl}/units`,
    GET: (id) => `${baseUrl}/units/${id}`,
    UPDATE: (id) => `${baseUrl}/units/${id}`,
    DELETE: (id) => `${baseUrl}/units/${id}`,
  },
  ROOMS: {
    LIST: `${baseUrl}/rooms`,
    CREATE: `${baseUrl}/rooms`,
    GET: (id) => `${baseUrl}/rooms/${id}`,
    UPDATE: (id) => `${baseUrl}/rooms/${id}`,
    DELETE: (id) => `${baseUrl}/rooms/${id}`,
  },
  WARDS: {
    LIST: `${baseUrl}/wards`,
    CREATE: `${baseUrl}/wards`,
    GET: (id) => `${baseUrl}/wards/${id}`,
    UPDATE: (id) => `${baseUrl}/wards/${id}`,
    DELETE: (id) => `${baseUrl}/wards/${id}`,
    GET_BEDS: (id) => `${baseUrl}/wards/${id}/beds`,
  },
  BEDS: {
    LIST: `${baseUrl}/beds`,
    CREATE: `${baseUrl}/beds`,
    GET: (id) => `${baseUrl}/beds/${id}`,
    UPDATE: (id) => `${baseUrl}/beds/${id}`,
    DELETE: (id) => `${baseUrl}/beds/${id}`,
  },
  CONTACTS: {
    LIST: `${baseUrl}/contacts`,
    CREATE: `${baseUrl}/contacts`,
    GET: (id) => `${baseUrl}/contacts/${id}`,
    UPDATE: (id) => `${baseUrl}/contacts/${id}`,
    DELETE: (id) => `${baseUrl}/contacts/${id}`,
  },
  USER_PROFILES: {
    LIST: `${baseUrl}/user-profiles`,
    CREATE: `${baseUrl}/user-profiles`,
    GET: (id) => `${baseUrl}/user-profiles/${id}`,
    UPDATE: (id) => `${baseUrl}/user-profiles/${id}`,
    DELETE: (id) => `${baseUrl}/user-profiles/${id}`,
  },
  ROLES: {
    LIST: `${baseUrl}/roles`,
    CREATE: `${baseUrl}/roles`,
    GET: (id) => `${baseUrl}/roles/${id}`,
    UPDATE: (id) => `${baseUrl}/roles/${id}`,
    DELETE: (id) => `${baseUrl}/roles/${id}`,
  },
  PERMISSIONS: {
    LIST: `${baseUrl}/permissions`,
    CREATE: `${baseUrl}/permissions`,
    GET: (id) => `${baseUrl}/permissions/${id}`,
    UPDATE: (id) => `${baseUrl}/permissions/${id}`,
    DELETE: (id) => `${baseUrl}/permissions/${id}`,
  },
  ROLE_PERMISSIONS: {
    LIST: `${baseUrl}/role-permissions`,
    CREATE: `${baseUrl}/role-permissions`,
    GET: (id) => `${baseUrl}/role-permissions/${id}`,
    UPDATE: (id) => `${baseUrl}/role-permissions/${id}`,
    DELETE: (id) => `${baseUrl}/role-permissions/${id}`,
  },
  USER_ROLES: {
    LIST: `${baseUrl}/user-roles`,
    CREATE: `${baseUrl}/user-roles`,
    GET: (id) => `${baseUrl}/user-roles/${id}`,
    UPDATE: (id) => `${baseUrl}/user-roles/${id}`,
    DELETE: (id) => `${baseUrl}/user-roles/${id}`,
  },
  API_KEYS: {
    LIST: `${baseUrl}/api-keys`,
    CREATE: `${baseUrl}/api-keys`,
    GET: (id) => `${baseUrl}/api-keys/${id}`,
    UPDATE: (id) => `${baseUrl}/api-keys/${id}`,
    DELETE: (id) => `${baseUrl}/api-keys/${id}`,
  },
  API_KEY_PERMISSIONS: {
    LIST: `${baseUrl}/api-key-permissions`,
    CREATE: `${baseUrl}/api-key-permissions`,
    GET: (id) => `${baseUrl}/api-key-permissions/${id}`,
    UPDATE: (id) => `${baseUrl}/api-key-permissions/${id}`,
    DELETE: (id) => `${baseUrl}/api-key-permissions/${id}`,
  },
  USER_MFAS: {
    LIST: `${baseUrl}/user-mfas`,
    CREATE: `${baseUrl}/user-mfas`,
    GET: (id) => `${baseUrl}/user-mfas/${id}`,
    UPDATE: (id) => `${baseUrl}/user-mfas/${id}`,
    DELETE: (id) => `${baseUrl}/user-mfas/${id}`,
    VERIFY: (id) => `${baseUrl}/user-mfas/${id}/verify`,
    ENABLE: (id) => `${baseUrl}/user-mfas/${id}/enable`,
    DISABLE: (id) => `${baseUrl}/user-mfas/${id}/disable`,
  },
  OAUTH_ACCOUNTS: {
    LIST: `${baseUrl}/oauth-accounts`,
    CREATE: `${baseUrl}/oauth-accounts`,
    GET: (id) => `${baseUrl}/oauth-accounts/${id}`,
    UPDATE: (id) => `${baseUrl}/oauth-accounts/${id}`,
    DELETE: (id) => `${baseUrl}/oauth-accounts/${id}`,
  },
  PATIENTS: {
    LIST: `${baseUrl}/patients`,
    CREATE: `${baseUrl}/patients`,
    GET: (id) => `${baseUrl}/patients/${id}`,
    UPDATE: (id) => `${baseUrl}/patients/${id}`,
    DELETE: (id) => `${baseUrl}/patients/${id}`,
  },
  PATIENT_IDENTIFIERS: {
    LIST: `${baseUrl}/patient-identifiers`,
    CREATE: `${baseUrl}/patient-identifiers`,
    GET: (id) => `${baseUrl}/patient-identifiers/${id}`,
    UPDATE: (id) => `${baseUrl}/patient-identifiers/${id}`,
    DELETE: (id) => `${baseUrl}/patient-identifiers/${id}`,
  },
  PATIENT_CONTACTS: {
    LIST: `${baseUrl}/patient-contacts`,
    CREATE: `${baseUrl}/patient-contacts`,
    GET: (id) => `${baseUrl}/patient-contacts/${id}`,
    UPDATE: (id) => `${baseUrl}/patient-contacts/${id}`,
    DELETE: (id) => `${baseUrl}/patient-contacts/${id}`,
  },
  PATIENT_GUARDIANS: {
    LIST: `${baseUrl}/patient-guardians`,
    CREATE: `${baseUrl}/patient-guardians`,
    GET: (id) => `${baseUrl}/patient-guardians/${id}`,
    UPDATE: (id) => `${baseUrl}/patient-guardians/${id}`,
    DELETE: (id) => `${baseUrl}/patient-guardians/${id}`,
  },
  PATIENT_ALLERGIES: {
    LIST: `${baseUrl}/patient-allergies`,
    CREATE: `${baseUrl}/patient-allergies`,
    GET: (id) => `${baseUrl}/patient-allergies/${id}`,
    UPDATE: (id) => `${baseUrl}/patient-allergies/${id}`,
    DELETE: (id) => `${baseUrl}/patient-allergies/${id}`,
  },
  PATIENT_MEDICAL_HISTORIES: {
    LIST: `${baseUrl}/patient-medical-histories`,
    CREATE: `${baseUrl}/patient-medical-histories`,
    GET: (id) => `${baseUrl}/patient-medical-histories/${id}`,
    UPDATE: (id) => `${baseUrl}/patient-medical-histories/${id}`,
    DELETE: (id) => `${baseUrl}/patient-medical-histories/${id}`,
  },
  PATIENT_DOCUMENTS: {
    LIST: `${baseUrl}/patient-documents`,
    CREATE: `${baseUrl}/patient-documents`,
    GET: (id) => `${baseUrl}/patient-documents/${id}`,
    UPDATE: (id) => `${baseUrl}/patient-documents/${id}`,
    DELETE: (id) => `${baseUrl}/patient-documents/${id}`,
  },
  CONSENTS: {
    LIST: `${baseUrl}/consents`,
    CREATE: `${baseUrl}/consents`,
    GET: (id) => `${baseUrl}/consents/${id}`,
    UPDATE: (id) => `${baseUrl}/consents/${id}`,
    DELETE: (id) => `${baseUrl}/consents/${id}`,
  },
  TERMS_ACCEPTANCES: {
    LIST: `${baseUrl}/terms-acceptances`,
    CREATE: `${baseUrl}/terms-acceptances`,
    GET: (id) => `${baseUrl}/terms-acceptances/${id}`,
    UPDATE: (id) => `${baseUrl}/terms-acceptances/${id}`,
    DELETE: (id) => `${baseUrl}/terms-acceptances/${id}`,
  },
  APPOINTMENTS: {
    LIST: `${baseUrl}/appointments`,
    CREATE: `${baseUrl}/appointments`,
    GET: (id) => `${baseUrl}/appointments/${id}`,
    UPDATE: (id) => `${baseUrl}/appointments/${id}`,
    DELETE: (id) => `${baseUrl}/appointments/${id}`,
  },
  APPOINTMENT_PARTICIPANTS: {
    LIST: `${baseUrl}/appointment-participants`,
    CREATE: `${baseUrl}/appointment-participants`,
    GET: (id) => `${baseUrl}/appointment-participants/${id}`,
    UPDATE: (id) => `${baseUrl}/appointment-participants/${id}`,
    DELETE: (id) => `${baseUrl}/appointment-participants/${id}`,
  },
  APPOINTMENT_REMINDERS: {
    LIST: `${baseUrl}/appointment-reminders`,
    CREATE: `${baseUrl}/appointment-reminders`,
    GET: (id) => `${baseUrl}/appointment-reminders/${id}`,
    UPDATE: (id) => `${baseUrl}/appointment-reminders/${id}`,
    DELETE: (id) => `${baseUrl}/appointment-reminders/${id}`,
  },
  PROVIDER_SCHEDULES: {
    LIST: `${baseUrl}/provider-schedules`,
    CREATE: `${baseUrl}/provider-schedules`,
    GET: (id) => `${baseUrl}/provider-schedules/${id}`,
    UPDATE: (id) => `${baseUrl}/provider-schedules/${id}`,
    DELETE: (id) => `${baseUrl}/provider-schedules/${id}`,
  },
  AVAILABILITY_SLOTS: {
    LIST: `${baseUrl}/availability-slots`,
    CREATE: `${baseUrl}/availability-slots`,
    GET: (id) => `${baseUrl}/availability-slots/${id}`,
    UPDATE: (id) => `${baseUrl}/availability-slots/${id}`,
    DELETE: (id) => `${baseUrl}/availability-slots/${id}`,
  },
  VISIT_QUEUES: {
    LIST: `${baseUrl}/visit-queues`,
    CREATE: `${baseUrl}/visit-queues`,
    GET: (id) => `${baseUrl}/visit-queues/${id}`,
    UPDATE: (id) => `${baseUrl}/visit-queues/${id}`,
    DELETE: (id) => `${baseUrl}/visit-queues/${id}`,
  },
  ENCOUNTERS: {
    LIST: `${baseUrl}/encounters`,
    CREATE: `${baseUrl}/encounters`,
    GET: (id) => `${baseUrl}/encounters/${id}`,
    UPDATE: (id) => `${baseUrl}/encounters/${id}`,
    DELETE: (id) => `${baseUrl}/encounters/${id}`,
  },
  CLINICAL_NOTES: {
    LIST: `${baseUrl}/clinical-notes`,
    CREATE: `${baseUrl}/clinical-notes`,
    GET: (id) => `${baseUrl}/clinical-notes/${id}`,
    UPDATE: (id) => `${baseUrl}/clinical-notes/${id}`,
    DELETE: (id) => `${baseUrl}/clinical-notes/${id}`,
  },
  DIAGNOSES: {
    LIST: `${baseUrl}/diagnoses`,
    CREATE: `${baseUrl}/diagnoses`,
    GET: (id) => `${baseUrl}/diagnoses/${id}`,
    UPDATE: (id) => `${baseUrl}/diagnoses/${id}`,
    DELETE: (id) => `${baseUrl}/diagnoses/${id}`,
  },
  PROCEDURES: {
    LIST: `${baseUrl}/procedures`,
    CREATE: `${baseUrl}/procedures`,
    GET: (id) => `${baseUrl}/procedures/${id}`,
    UPDATE: (id) => `${baseUrl}/procedures/${id}`,
    DELETE: (id) => `${baseUrl}/procedures/${id}`,
  },
  VITAL_SIGNS: {
    LIST: `${baseUrl}/vital-signs`,
    CREATE: `${baseUrl}/vital-signs`,
    GET: (id) => `${baseUrl}/vital-signs/${id}`,
    UPDATE: (id) => `${baseUrl}/vital-signs/${id}`,
    DELETE: (id) => `${baseUrl}/vital-signs/${id}`,
  },
  CARE_PLANS: {
    LIST: `${baseUrl}/care-plans`,
    CREATE: `${baseUrl}/care-plans`,
    GET: (id) => `${baseUrl}/care-plans/${id}`,
    UPDATE: (id) => `${baseUrl}/care-plans/${id}`,
    DELETE: (id) => `${baseUrl}/care-plans/${id}`,
  },
  CLINICAL_ALERTS: {
    LIST: `${baseUrl}/clinical-alerts`,
    CREATE: `${baseUrl}/clinical-alerts`,
    GET: (id) => `${baseUrl}/clinical-alerts/${id}`,
    UPDATE: (id) => `${baseUrl}/clinical-alerts/${id}`,
    DELETE: (id) => `${baseUrl}/clinical-alerts/${id}`,
  },
  REFERRALS: {
    LIST: `${baseUrl}/referrals`,
    CREATE: `${baseUrl}/referrals`,
    GET: (id) => `${baseUrl}/referrals/${id}`,
    UPDATE: (id) => `${baseUrl}/referrals/${id}`,
    DELETE: (id) => `${baseUrl}/referrals/${id}`,
  },
  FOLLOW_UPS: {
    LIST: `${baseUrl}/follow-ups`,
    CREATE: `${baseUrl}/follow-ups`,
    GET: (id) => `${baseUrl}/follow-ups/${id}`,
    UPDATE: (id) => `${baseUrl}/follow-ups/${id}`,
    DELETE: (id) => `${baseUrl}/follow-ups/${id}`,
  },
  ADMISSIONS: {
    LIST: `${baseUrl}/admissions`,
    CREATE: `${baseUrl}/admissions`,
    GET: (id) => `${baseUrl}/admissions/${id}`,
    UPDATE: (id) => `${baseUrl}/admissions/${id}`,
    DELETE: (id) => `${baseUrl}/admissions/${id}`,
  },
  BED_ASSIGNMENTS: {
    LIST: `${baseUrl}/bed-assignments`,
    CREATE: `${baseUrl}/bed-assignments`,
    GET: (id) => `${baseUrl}/bed-assignments/${id}`,
    UPDATE: (id) => `${baseUrl}/bed-assignments/${id}`,
    DELETE: (id) => `${baseUrl}/bed-assignments/${id}`,
  },
  WARD_ROUNDS: {
    LIST: `${baseUrl}/ward-rounds`,
    CREATE: `${baseUrl}/ward-rounds`,
    GET: (id) => `${baseUrl}/ward-rounds/${id}`,
    UPDATE: (id) => `${baseUrl}/ward-rounds/${id}`,
    DELETE: (id) => `${baseUrl}/ward-rounds/${id}`,
  },
  NURSING_NOTES: {
    LIST: `${baseUrl}/nursing-notes`,
    CREATE: `${baseUrl}/nursing-notes`,
    GET: (id) => `${baseUrl}/nursing-notes/${id}`,
    UPDATE: (id) => `${baseUrl}/nursing-notes/${id}`,
    DELETE: (id) => `${baseUrl}/nursing-notes/${id}`,
  },
  MEDICATION_ADMINISTRATIONS: {
    LIST: `${baseUrl}/medication-administrations`,
    CREATE: `${baseUrl}/medication-administrations`,
    GET: (id) => `${baseUrl}/medication-administrations/${id}`,
    UPDATE: (id) => `${baseUrl}/medication-administrations/${id}`,
    DELETE: (id) => `${baseUrl}/medication-administrations/${id}`,
  },
  DISCHARGE_SUMMARIES: {
    LIST: `${baseUrl}/discharge-summaries`,
    CREATE: `${baseUrl}/discharge-summaries`,
    GET: (id) => `${baseUrl}/discharge-summaries/${id}`,
    UPDATE: (id) => `${baseUrl}/discharge-summaries/${id}`,
    DELETE: (id) => `${baseUrl}/discharge-summaries/${id}`,
  },
  TRANSFER_REQUESTS: {
    LIST: `${baseUrl}/transfer-requests`,
    CREATE: `${baseUrl}/transfer-requests`,
    GET: (id) => `${baseUrl}/transfer-requests/${id}`,
    UPDATE: (id) => `${baseUrl}/transfer-requests/${id}`,
    DELETE: (id) => `${baseUrl}/transfer-requests/${id}`,
  },
  ICU_STAYS: {
    LIST: `${baseUrl}/icu-stays`,
    CREATE: `${baseUrl}/icu-stays`,
    GET: (id) => `${baseUrl}/icu-stays/${id}`,
    UPDATE: (id) => `${baseUrl}/icu-stays/${id}`,
    DELETE: (id) => `${baseUrl}/icu-stays/${id}`,
  },
  ICU_OBSERVATIONS: {
    LIST: `${baseUrl}/icu-observations`,
    CREATE: `${baseUrl}/icu-observations`,
    GET: (id) => `${baseUrl}/icu-observations/${id}`,
    UPDATE: (id) => `${baseUrl}/icu-observations/${id}`,
    DELETE: (id) => `${baseUrl}/icu-observations/${id}`,
  },
  CRITICAL_ALERTS: {
    LIST: `${baseUrl}/critical-alerts`,
    CREATE: `${baseUrl}/critical-alerts`,
    GET: (id) => `${baseUrl}/critical-alerts/${id}`,
    UPDATE: (id) => `${baseUrl}/critical-alerts/${id}`,
    DELETE: (id) => `${baseUrl}/critical-alerts/${id}`,
  },
  THEATRE_CASES: {
    LIST: `${baseUrl}/theatre-cases`,
    CREATE: `${baseUrl}/theatre-cases`,
    GET: (id) => `${baseUrl}/theatre-cases/${id}`,
    UPDATE: (id) => `${baseUrl}/theatre-cases/${id}`,
    DELETE: (id) => `${baseUrl}/theatre-cases/${id}`,
  },
  ANESTHESIA_RECORDS: {
    LIST: `${baseUrl}/anesthesia-records`,
    CREATE: `${baseUrl}/anesthesia-records`,
    GET: (id) => `${baseUrl}/anesthesia-records/${id}`,
    UPDATE: (id) => `${baseUrl}/anesthesia-records/${id}`,
    DELETE: (id) => `${baseUrl}/anesthesia-records/${id}`,
  },
  POST_OP_NOTES: {
    LIST: `${baseUrl}/post-op-notes`,
    CREATE: `${baseUrl}/post-op-notes`,
    GET: (id) => `${baseUrl}/post-op-notes/${id}`,
    UPDATE: (id) => `${baseUrl}/post-op-notes/${id}`,
    DELETE: (id) => `${baseUrl}/post-op-notes/${id}`,
  },
  LAB_TESTS: {
    LIST: `${baseUrl}/lab-tests`,
    CREATE: `${baseUrl}/lab-tests`,
    GET: (id) => `${baseUrl}/lab-tests/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-tests/${id}`,
    DELETE: (id) => `${baseUrl}/lab-tests/${id}`,
  },
  LAB_PANELS: {
    LIST: `${baseUrl}/lab-panels`,
    CREATE: `${baseUrl}/lab-panels`,
    GET: (id) => `${baseUrl}/lab-panels/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-panels/${id}`,
    DELETE: (id) => `${baseUrl}/lab-panels/${id}`,
  },
  LAB_ORDERS: {
    LIST: `${baseUrl}/lab-orders`,
    CREATE: `${baseUrl}/lab-orders`,
    GET: (id) => `${baseUrl}/lab-orders/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-orders/${id}`,
    DELETE: (id) => `${baseUrl}/lab-orders/${id}`,
  },
  LAB_ORDER_ITEMS: {
    LIST: `${baseUrl}/lab-order-items`,
    CREATE: `${baseUrl}/lab-order-items`,
    GET: (id) => `${baseUrl}/lab-order-items/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-order-items/${id}`,
    DELETE: (id) => `${baseUrl}/lab-order-items/${id}`,
  },
  LAB_SAMPLES: {
    LIST: `${baseUrl}/lab-samples`,
    CREATE: `${baseUrl}/lab-samples`,
    GET: (id) => `${baseUrl}/lab-samples/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-samples/${id}`,
    DELETE: (id) => `${baseUrl}/lab-samples/${id}`,
  },
  LAB_RESULTS: {
    LIST: `${baseUrl}/lab-results`,
    CREATE: `${baseUrl}/lab-results`,
    GET: (id) => `${baseUrl}/lab-results/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-results/${id}`,
    DELETE: (id) => `${baseUrl}/lab-results/${id}`,
  },
  LAB_QC_LOGS: {
    LIST: `${baseUrl}/lab-qc-logs`,
    CREATE: `${baseUrl}/lab-qc-logs`,
    GET: (id) => `${baseUrl}/lab-qc-logs/${id}`,
    UPDATE: (id) => `${baseUrl}/lab-qc-logs/${id}`,
    DELETE: (id) => `${baseUrl}/lab-qc-logs/${id}`,
  },
  RADIOLOGY_TESTS: {
    LIST: `${baseUrl}/radiology-tests`,
    CREATE: `${baseUrl}/radiology-tests`,
    GET: (id) => `${baseUrl}/radiology-tests/${id}`,
    UPDATE: (id) => `${baseUrl}/radiology-tests/${id}`,
    DELETE: (id) => `${baseUrl}/radiology-tests/${id}`,
  },
  RADIOLOGY_ORDERS: {
    LIST: `${baseUrl}/radiology-orders`,
    CREATE: `${baseUrl}/radiology-orders`,
    GET: (id) => `${baseUrl}/radiology-orders/${id}`,
    UPDATE: (id) => `${baseUrl}/radiology-orders/${id}`,
    DELETE: (id) => `${baseUrl}/radiology-orders/${id}`,
  },
  RADIOLOGY_RESULTS: {
    LIST: `${baseUrl}/radiology-results`,
    CREATE: `${baseUrl}/radiology-results`,
    GET: (id) => `${baseUrl}/radiology-results/${id}`,
    UPDATE: (id) => `${baseUrl}/radiology-results/${id}`,
    DELETE: (id) => `${baseUrl}/radiology-results/${id}`,
  },
  IMAGING_STUDIES: {
    LIST: `${baseUrl}/imaging-studies`,
    CREATE: `${baseUrl}/imaging-studies`,
    GET: (id) => `${baseUrl}/imaging-studies/${id}`,
    UPDATE: (id) => `${baseUrl}/imaging-studies/${id}`,
    DELETE: (id) => `${baseUrl}/imaging-studies/${id}`,
  },
  IMAGING_ASSETS: {
    LIST: `${baseUrl}/imaging-assets`,
    CREATE: `${baseUrl}/imaging-assets`,
    GET: (id) => `${baseUrl}/imaging-assets/${id}`,
    UPDATE: (id) => `${baseUrl}/imaging-assets/${id}`,
    DELETE: (id) => `${baseUrl}/imaging-assets/${id}`,
  },
  PACS_LINKS: {
    LIST: `${baseUrl}/pacs-links`,
    CREATE: `${baseUrl}/pacs-links`,
    GET: (id) => `${baseUrl}/pacs-links/${id}`,
    UPDATE: (id) => `${baseUrl}/pacs-links/${id}`,
    DELETE: (id) => `${baseUrl}/pacs-links/${id}`,
  },
  DRUGS: {
    LIST: `${baseUrl}/drugs`,
    CREATE: `${baseUrl}/drugs`,
    GET: (id) => `${baseUrl}/drugs/${id}`,
    UPDATE: (id) => `${baseUrl}/drugs/${id}`,
    DELETE: (id) => `${baseUrl}/drugs/${id}`,
  },
  DRUG_BATCHES: {
    LIST: `${baseUrl}/drug-batches`,
    CREATE: `${baseUrl}/drug-batches`,
    GET: (id) => `${baseUrl}/drug-batches/${id}`,
    UPDATE: (id) => `${baseUrl}/drug-batches/${id}`,
    DELETE: (id) => `${baseUrl}/drug-batches/${id}`,
  },
  FORMULARY_ITEMS: {
    LIST: `${baseUrl}/formulary-items`,
    CREATE: `${baseUrl}/formulary-items`,
    GET: (id) => `${baseUrl}/formulary-items/${id}`,
    UPDATE: (id) => `${baseUrl}/formulary-items/${id}`,
    DELETE: (id) => `${baseUrl}/formulary-items/${id}`,
  },
  PHARMACY_ORDERS: {
    LIST: `${baseUrl}/pharmacy-orders`,
    CREATE: `${baseUrl}/pharmacy-orders`,
    GET: (id) => `${baseUrl}/pharmacy-orders/${id}`,
    UPDATE: (id) => `${baseUrl}/pharmacy-orders/${id}`,
    DELETE: (id) => `${baseUrl}/pharmacy-orders/${id}`,
  },
  PHARMACY_ORDER_ITEMS: {
    LIST: `${baseUrl}/pharmacy-order-items`,
    CREATE: `${baseUrl}/pharmacy-order-items`,
    GET: (id) => `${baseUrl}/pharmacy-order-items/${id}`,
    UPDATE: (id) => `${baseUrl}/pharmacy-order-items/${id}`,
    DELETE: (id) => `${baseUrl}/pharmacy-order-items/${id}`,
  },
  DISPENSE_LOGS: {
    LIST: `${baseUrl}/dispense-logs`,
    CREATE: `${baseUrl}/dispense-logs`,
    GET: (id) => `${baseUrl}/dispense-logs/${id}`,
    UPDATE: (id) => `${baseUrl}/dispense-logs/${id}`,
    DELETE: (id) => `${baseUrl}/dispense-logs/${id}`,
  },
  ADVERSE_EVENTS: {
    LIST: `${baseUrl}/adverse-events`,
    CREATE: `${baseUrl}/adverse-events`,
    GET: (id) => `${baseUrl}/adverse-events/${id}`,
    UPDATE: (id) => `${baseUrl}/adverse-events/${id}`,
    DELETE: (id) => `${baseUrl}/adverse-events/${id}`,
  },
  INVENTORY_ITEMS: {
    LIST: `${baseUrl}/inventory-items`,
    CREATE: `${baseUrl}/inventory-items`,
    GET: (id) => `${baseUrl}/inventory-items/${id}`,
    UPDATE: (id) => `${baseUrl}/inventory-items/${id}`,
    DELETE: (id) => `${baseUrl}/inventory-items/${id}`,
  },
  INVENTORY_STOCKS: {
    LIST: `${baseUrl}/inventory-stocks`,
    CREATE: `${baseUrl}/inventory-stocks`,
    GET: (id) => `${baseUrl}/inventory-stocks/${id}`,
    UPDATE: (id) => `${baseUrl}/inventory-stocks/${id}`,
    DELETE: (id) => `${baseUrl}/inventory-stocks/${id}`,
  },
  STOCK_MOVEMENTS: {
    LIST: `${baseUrl}/stock-movements`,
    CREATE: `${baseUrl}/stock-movements`,
    GET: (id) => `${baseUrl}/stock-movements/${id}`,
    UPDATE: (id) => `${baseUrl}/stock-movements/${id}`,
    DELETE: (id) => `${baseUrl}/stock-movements/${id}`,
  },
  SUPPLIERS: {
    LIST: `${baseUrl}/suppliers`,
    CREATE: `${baseUrl}/suppliers`,
    GET: (id) => `${baseUrl}/suppliers/${id}`,
    UPDATE: (id) => `${baseUrl}/suppliers/${id}`,
    DELETE: (id) => `${baseUrl}/suppliers/${id}`,
  },
  PURCHASE_REQUESTS: {
    LIST: `${baseUrl}/purchase-requests`,
    CREATE: `${baseUrl}/purchase-requests`,
    GET: (id) => `${baseUrl}/purchase-requests/${id}`,
    UPDATE: (id) => `${baseUrl}/purchase-requests/${id}`,
    DELETE: (id) => `${baseUrl}/purchase-requests/${id}`,
  },
  PURCHASE_ORDERS: {
    LIST: `${baseUrl}/purchase-orders`,
    CREATE: `${baseUrl}/purchase-orders`,
    GET: (id) => `${baseUrl}/purchase-orders/${id}`,
    UPDATE: (id) => `${baseUrl}/purchase-orders/${id}`,
    DELETE: (id) => `${baseUrl}/purchase-orders/${id}`,
  },
  GOODS_RECEIPTS: {
    LIST: `${baseUrl}/goods-receipts`,
    CREATE: `${baseUrl}/goods-receipts`,
    GET: (id) => `${baseUrl}/goods-receipts/${id}`,
    UPDATE: (id) => `${baseUrl}/goods-receipts/${id}`,
    DELETE: (id) => `${baseUrl}/goods-receipts/${id}`,
  },
  STOCK_ADJUSTMENTS: {
    LIST: `${baseUrl}/stock-adjustments`,
    CREATE: `${baseUrl}/stock-adjustments`,
    GET: (id) => `${baseUrl}/stock-adjustments/${id}`,
    UPDATE: (id) => `${baseUrl}/stock-adjustments/${id}`,
    DELETE: (id) => `${baseUrl}/stock-adjustments/${id}`,
  },
  EMERGENCY_CASES: {
    LIST: `${baseUrl}/emergency-cases`,
    CREATE: `${baseUrl}/emergency-cases`,
    GET: (id) => `${baseUrl}/emergency-cases/${id}`,
    UPDATE: (id) => `${baseUrl}/emergency-cases/${id}`,
    DELETE: (id) => `${baseUrl}/emergency-cases/${id}`,
  },
  TRIAGE_ASSESSMENTS: {
    LIST: `${baseUrl}/triage-assessments`,
    CREATE: `${baseUrl}/triage-assessments`,
    GET: (id) => `${baseUrl}/triage-assessments/${id}`,
    UPDATE: (id) => `${baseUrl}/triage-assessments/${id}`,
    DELETE: (id) => `${baseUrl}/triage-assessments/${id}`,
  },
  EMERGENCY_RESPONSES: {
    LIST: `${baseUrl}/emergency-responses`,
    CREATE: `${baseUrl}/emergency-responses`,
    GET: (id) => `${baseUrl}/emergency-responses/${id}`,
    UPDATE: (id) => `${baseUrl}/emergency-responses/${id}`,
    DELETE: (id) => `${baseUrl}/emergency-responses/${id}`,
  },
  AMBULANCES: {
    LIST: `${baseUrl}/ambulances`,
    CREATE: `${baseUrl}/ambulances`,
    GET: (id) => `${baseUrl}/ambulances/${id}`,
    UPDATE: (id) => `${baseUrl}/ambulances/${id}`,
    DELETE: (id) => `${baseUrl}/ambulances/${id}`,
  },
  AMBULANCE_DISPATCHES: {
    LIST: `${baseUrl}/ambulance-dispatches`,
    CREATE: `${baseUrl}/ambulance-dispatches`,
    GET: (id) => `${baseUrl}/ambulance-dispatches/${id}`,
    UPDATE: (id) => `${baseUrl}/ambulance-dispatches/${id}`,
    DELETE: (id) => `${baseUrl}/ambulance-dispatches/${id}`,
  },
  AMBULANCE_TRIPS: {
    LIST: `${baseUrl}/ambulance-trips`,
    CREATE: `${baseUrl}/ambulance-trips`,
    GET: (id) => `${baseUrl}/ambulance-trips/${id}`,
    UPDATE: (id) => `${baseUrl}/ambulance-trips/${id}`,
    DELETE: (id) => `${baseUrl}/ambulance-trips/${id}`,
  },
  INVOICES: {
    LIST: `${baseUrl}/invoices`,
    CREATE: `${baseUrl}/invoices`,
    GET: (id) => `${baseUrl}/invoices/${id}`,
    UPDATE: (id) => `${baseUrl}/invoices/${id}`,
    DELETE: (id) => `${baseUrl}/invoices/${id}`,
  },
  INVOICE_ITEMS: {
    LIST: `${baseUrl}/invoice-items`,
    CREATE: `${baseUrl}/invoice-items`,
    GET: (id) => `${baseUrl}/invoice-items/${id}`,
    UPDATE: (id) => `${baseUrl}/invoice-items/${id}`,
    DELETE: (id) => `${baseUrl}/invoice-items/${id}`,
  },
  REFUNDS: {
    LIST: `${baseUrl}/refunds`,
    CREATE: `${baseUrl}/refunds`,
    GET: (id) => `${baseUrl}/refunds/${id}`,
    UPDATE: (id) => `${baseUrl}/refunds/${id}`,
    DELETE: (id) => `${baseUrl}/refunds/${id}`,
  },
  PRICING_RULES: {
    LIST: `${baseUrl}/pricing-rules`,
    CREATE: `${baseUrl}/pricing-rules`,
    GET: (id) => `${baseUrl}/pricing-rules/${id}`,
    UPDATE: (id) => `${baseUrl}/pricing-rules/${id}`,
    DELETE: (id) => `${baseUrl}/pricing-rules/${id}`,
  },
  COVERAGE_PLANS: {
    LIST: `${baseUrl}/coverage-plans`,
    CREATE: `${baseUrl}/coverage-plans`,
    GET: (id) => `${baseUrl}/coverage-plans/${id}`,
    UPDATE: (id) => `${baseUrl}/coverage-plans/${id}`,
    DELETE: (id) => `${baseUrl}/coverage-plans/${id}`,
  },
  INSURANCE_CLAIMS: {
    LIST: `${baseUrl}/insurance-claims`,
    CREATE: `${baseUrl}/insurance-claims`,
    GET: (id) => `${baseUrl}/insurance-claims/${id}`,
    UPDATE: (id) => `${baseUrl}/insurance-claims/${id}`,
    DELETE: (id) => `${baseUrl}/insurance-claims/${id}`,
  },
  PRE_AUTHORIZATIONS: {
    LIST: `${baseUrl}/pre-authorizations`,
    CREATE: `${baseUrl}/pre-authorizations`,
    GET: (id) => `${baseUrl}/pre-authorizations/${id}`,
    UPDATE: (id) => `${baseUrl}/pre-authorizations/${id}`,
    DELETE: (id) => `${baseUrl}/pre-authorizations/${id}`,
  },
  BILLING_ADJUSTMENTS: {
    LIST: `${baseUrl}/billing-adjustments`,
    CREATE: `${baseUrl}/billing-adjustments`,
    GET: (id) => `${baseUrl}/billing-adjustments/${id}`,
    UPDATE: (id) => `${baseUrl}/billing-adjustments/${id}`,
    DELETE: (id) => `${baseUrl}/billing-adjustments/${id}`,
  },
  STAFF_PROFILES: {
    LIST: `${baseUrl}/staff-profiles`,
    CREATE: `${baseUrl}/staff-profiles`,
    GET: (id) => `${baseUrl}/staff-profiles/${id}`,
    UPDATE: (id) => `${baseUrl}/staff-profiles/${id}`,
    DELETE: (id) => `${baseUrl}/staff-profiles/${id}`,
  },
  STAFF_ASSIGNMENTS: {
    LIST: `${baseUrl}/staff-assignments`,
    CREATE: `${baseUrl}/staff-assignments`,
    GET: (id) => `${baseUrl}/staff-assignments/${id}`,
    UPDATE: (id) => `${baseUrl}/staff-assignments/${id}`,
    DELETE: (id) => `${baseUrl}/staff-assignments/${id}`,
  },
  STAFF_LEAVES: {
    LIST: `${baseUrl}/staff-leaves`,
    CREATE: `${baseUrl}/staff-leaves`,
    GET: (id) => `${baseUrl}/staff-leaves/${id}`,
    UPDATE: (id) => `${baseUrl}/staff-leaves/${id}`,
    DELETE: (id) => `${baseUrl}/staff-leaves/${id}`,
  },
  SHIFTS: {
    LIST: `${baseUrl}/shifts`,
    CREATE: `${baseUrl}/shifts`,
    GET: (id) => `${baseUrl}/shifts/${id}`,
    UPDATE: (id) => `${baseUrl}/shifts/${id}`,
    DELETE: (id) => `${baseUrl}/shifts/${id}`,
  },
  SHIFT_ASSIGNMENTS: {
    LIST: `${baseUrl}/shift-assignments`,
    CREATE: `${baseUrl}/shift-assignments`,
    GET: (id) => `${baseUrl}/shift-assignments/${id}`,
    UPDATE: (id) => `${baseUrl}/shift-assignments/${id}`,
    DELETE: (id) => `${baseUrl}/shift-assignments/${id}`,
  },
  SHIFT_SWAP_REQUESTS: {
    LIST: `${baseUrl}/shift-swap-requests`,
    CREATE: `${baseUrl}/shift-swap-requests`,
    GET: (id) => `${baseUrl}/shift-swap-requests/${id}`,
    UPDATE: (id) => `${baseUrl}/shift-swap-requests/${id}`,
    DELETE: (id) => `${baseUrl}/shift-swap-requests/${id}`,
  },
  PAYROLL_RUNS: {
    LIST: `${baseUrl}/payroll-runs`,
    CREATE: `${baseUrl}/payroll-runs`,
    GET: (id) => `${baseUrl}/payroll-runs/${id}`,
    UPDATE: (id) => `${baseUrl}/payroll-runs/${id}`,
    DELETE: (id) => `${baseUrl}/payroll-runs/${id}`,
  },
  PAYROLL_ITEMS: {
    LIST: `${baseUrl}/payroll-items`,
    CREATE: `${baseUrl}/payroll-items`,
    GET: (id) => `${baseUrl}/payroll-items/${id}`,
    UPDATE: (id) => `${baseUrl}/payroll-items/${id}`,
    DELETE: (id) => `${baseUrl}/payroll-items/${id}`,
  },
  HOUSEKEEPING_TASKS: {
    LIST: `${baseUrl}/housekeeping-tasks`,
    CREATE: `${baseUrl}/housekeeping-tasks`,
    GET: (id) => `${baseUrl}/housekeeping-tasks/${id}`,
    UPDATE: (id) => `${baseUrl}/housekeeping-tasks/${id}`,
    DELETE: (id) => `${baseUrl}/housekeeping-tasks/${id}`,
  },
  HOUSEKEEPING_SCHEDULES: {
    LIST: `${baseUrl}/housekeeping-schedules`,
    CREATE: `${baseUrl}/housekeeping-schedules`,
    GET: (id) => `${baseUrl}/housekeeping-schedules/${id}`,
    UPDATE: (id) => `${baseUrl}/housekeeping-schedules/${id}`,
    DELETE: (id) => `${baseUrl}/housekeeping-schedules/${id}`,
  },
  MAINTENANCE_REQUESTS: {
    LIST: `${baseUrl}/maintenance-requests`,
    CREATE: `${baseUrl}/maintenance-requests`,
    GET: (id) => `${baseUrl}/maintenance-requests/${id}`,
    UPDATE: (id) => `${baseUrl}/maintenance-requests/${id}`,
    DELETE: (id) => `${baseUrl}/maintenance-requests/${id}`,
  },
  ASSETS: {
    LIST: `${baseUrl}/assets`,
    CREATE: `${baseUrl}/assets`,
    GET: (id) => `${baseUrl}/assets/${id}`,
    UPDATE: (id) => `${baseUrl}/assets/${id}`,
    DELETE: (id) => `${baseUrl}/assets/${id}`,
  },
  ASSET_SERVICE_LOGS: {
    LIST: `${baseUrl}/asset-service-logs`,
    CREATE: `${baseUrl}/asset-service-logs`,
    GET: (id) => `${baseUrl}/asset-service-logs/${id}`,
    UPDATE: (id) => `${baseUrl}/asset-service-logs/${id}`,
    DELETE: (id) => `${baseUrl}/asset-service-logs/${id}`,
  },
  USERS: {
    GET: (id) => `${baseUrl}/users/${id}`,
    LIST: `${baseUrl}/users`,
    UPDATE: (id) => `${baseUrl}/users/${id}`,
    DELETE: (id) => `${baseUrl}/users/${id}`,
    GET_PROFILE: `${baseUrl}/users/me`,
    UPDATE_PROFILE: `${baseUrl}/users/me`,
  },
  PRODUCTS: {
    SEARCH: `${baseUrl}/products/search`,
    LIST: `${baseUrl}/products`,
    GET: (id) => `${baseUrl}/products/${id}`,
    CREATE: `${baseUrl}/products`,
    UPDATE: (id) => `${baseUrl}/products/${id}`,
    DELETE: (id) => `${baseUrl}/products/${id}`,
    PUBLISH: (id) => `${baseUrl}/products/${id}/publish`,
    ATTRIBUTES: (id) => `${baseUrl}/products/${id}/attributes`,
    ADD_ATTRIBUTE: (id) => `${baseUrl}/products/${id}/attributes`,
    MEDIA: (id) => `${baseUrl}/products/${id}/media`,
    ADD_MEDIA: (id) => `${baseUrl}/products/${id}/media`,
    SUPPLIERS: (id) => `${baseUrl}/products/${id}/suppliers`,
    ADD_SUPPLIER: (id) => `${baseUrl}/products/${id}/suppliers`,
    COMPATIBILITY: (id) => `${baseUrl}/products/${id}/compatibility`,
    PRICE_HISTORY: (id) => `${baseUrl}/products/${id}/price-history`,
    COMMENTS: (id) => `${baseUrl}/products/${id}/comments`,
    ADD_COMMENT: (id) => `${baseUrl}/products/${id}/comments`,
    INVENTORY: (id) => `${baseUrl}/products/${id}/inventory`,
  },
  CARTS: {
    LIST: `${baseUrl}/carts`,
    CREATE: `${baseUrl}/carts`,
    GET: (id) => `${baseUrl}/carts/${id}`,
    UPDATE: (id) => `${baseUrl}/carts/${id}`,
    DELETE: (id) => `${baseUrl}/carts/${id}`,
    GET_ITEMS: (id) => `${baseUrl}/carts/${id}/items`,
    ADD_ITEM: (id) => `${baseUrl}/carts/${id}/items`,
    UPDATE_ITEM: (id, productId) => `${baseUrl}/carts/${id}/items/${productId}`,
    REMOVE_ITEM: (id, productId) => `${baseUrl}/carts/${id}/items/${productId}`,
    REQUEST_QUOTE: (id) => `${baseUrl}/carts/${id}/request-quote`,
  },
  ORDERS: {
    CREATE: `${baseUrl}/orders`,
    LIST: `${baseUrl}/orders`,
    GET: (id) => `${baseUrl}/orders/${id}`,
    UPDATE: (id) => `${baseUrl}/orders/${id}`,
    DELETE: (id) => `${baseUrl}/orders/${id}`,
    GET_ITEMS: (id) => `${baseUrl}/orders/${id}/items`,
    GET_PAYMENTS: (id) => `${baseUrl}/orders/${id}/payments`,
    GET_SHIPMENTS: (id) => `${baseUrl}/orders/${id}/shipments`,
    GET_RETURNS: (id) => `${baseUrl}/orders/${id}/returns`,
    UPDATE_STATUS: (id) => `${baseUrl}/orders/${id}/status`,
    CANCEL: (id) => `${baseUrl}/orders/${id}/cancel`,
    GET_TRACKING: (id) => `${baseUrl}/orders/${id}/tracking`,
  },
  PAYMENTS: {
    CREATE: `${baseUrl}/payments`,
    LIST: `${baseUrl}/payments`,
    GET: (id) => `${baseUrl}/payments/${id}`,
    UPDATE: (id) => `${baseUrl}/payments/${id}`,
    DELETE: (id) => `${baseUrl}/payments/${id}`,
    GET_REFUNDS: (id) => `${baseUrl}/payments/${id}/refunds`,
    REFUND: (id) => `${baseUrl}/payments/${id}/refund`,
  },
  ORDER_PAYMENT_METHODS: {
    LIST: `${baseUrl}/order-payment-methods`,
    CREATE: `${baseUrl}/order-payment-methods`,
    GET: (id) => `${baseUrl}/order-payment-methods/${id}`,
    UPDATE: (id) => `${baseUrl}/order-payment-methods/${id}`,
    DELETE: (id) => `${baseUrl}/order-payment-methods/${id}`,
    SET_DEFAULT: (id) => `${baseUrl}/order-payment-methods/${id}/set-default`,
    ACTIVATE: (id) => `${baseUrl}/order-payment-methods/${id}/activate`,
    DEACTIVATE: (id) => `${baseUrl}/order-payment-methods/${id}/deactivate`,
    GET_BY_USER: (userId) => `${baseUrl}/order-payment-methods/user/${userId}`,
    GET_BY_COMPANY: (companyId) => `${baseUrl}/order-payment-methods/company/${companyId}`,
  },
  PAYMENT_METHOD_REQUESTS: {
    LIST: `${baseUrl}/payment-method-requests`,
    CREATE: `${baseUrl}/payment-method-requests`,
    GET: (id) => `${baseUrl}/payment-method-requests/${id}`,
    UPDATE: (id) => `${baseUrl}/payment-method-requests/${id}`,
    DELETE: (id) => `${baseUrl}/payment-method-requests/${id}`,
  },
  SHOPS: {
    CREATE: `${baseUrl}/shops`,
    LIST: `${baseUrl}/shops`,
    GET: (id) => `${baseUrl}/shops/${id}`,
    UPDATE: (id) => `${baseUrl}/shops/${id}`,
    DELETE: (id) => `${baseUrl}/shops/${id}`,
    GET_PRODUCTS: (id) => `${baseUrl}/shops/${id}/products`,
    GET_MEDIA: (id) => `${baseUrl}/shops/${id}/media`,
    ADD_MEDIA: (id) => `${baseUrl}/shops/${id}/media`,
    DELETE_MEDIA: (id, mediaId) => `${baseUrl}/shops/${id}/media/${mediaId}`,
    GET_QUOTE_REQUESTS: (id) => `${baseUrl}/shops/${id}/quote-requests`,
    GET_ORDERS: (id) => `${baseUrl}/shops/${id}/orders`,
    GET_OWNER: (id) => `${baseUrl}/shops/${id}/owner`,
  },
  SUBSCRIPTIONS: {
    GET_PLANS: `${baseUrl}/subscriptions/plans`,
    SUBSCRIBE: `${baseUrl}/subscriptions`,
    GET: (id) => `${baseUrl}/subscriptions/${id}`,
    GET_CURRENT: `${baseUrl}/subscriptions/current`,
    UPGRADE: (id) => `${baseUrl}/subscriptions/${id}/upgrade`,
    DOWNGRADE: (id) => `${baseUrl}/subscriptions/${id}/downgrade`,
    CANCEL: (id) => `${baseUrl}/subscriptions/${id}/cancel`,
  },
  SUBSCRIPTION_USAGE: {
    LIST: `${baseUrl}/subscription-usage`,
    CREATE: `${baseUrl}/subscription-usage`,
    GET: (id) => `${baseUrl}/subscription-usage/${id}`,
    UPDATE: (id) => `${baseUrl}/subscription-usage/${id}`,
    DELETE: (id) => `${baseUrl}/subscription-usage/${id}`,
    GET_BY_SUBSCRIPTION: (subscriptionId) => `${baseUrl}/subscription-usage/subscription/${subscriptionId}`,
    GET_BY_FEATURE: (featureType) => `${baseUrl}/subscription-usage/feature/${featureType}`,
  },
  QUOTE_REQUESTS: {
    LIST: `${baseUrl}/quote-requests`,
    CREATE: `${baseUrl}/quote-requests`,
    GET: (id) => `${baseUrl}/quote-requests/${id}`,
    UPDATE: (id) => `${baseUrl}/quote-requests/${id}`,
    DELETE: (id) => `${baseUrl}/quote-requests/${id}`,
    GET_ITEMS: (id) => `${baseUrl}/quote-requests/${id}/items`,
    ADD_ITEM: (id) => `${baseUrl}/quote-requests/${id}/items`,
    GET_COMMENTS: (id) => `${baseUrl}/quote-requests/${id}/comments`,
    ADD_COMMENT: (id) => `${baseUrl}/quote-requests/${id}/comments`,
    GET_MEDIA: (id) => `${baseUrl}/quote-requests/${id}/media`,
    ADD_MEDIA: (id) => `${baseUrl}/quote-requests/${id}/media`,
    ACCEPT: (id) => `${baseUrl}/quote-requests/${id}/accept`,
  },
  PRODUCT_REVIEWS: {
    LIST: `${baseUrl}/product-reviews`,
    CREATE: `${baseUrl}/product-reviews`,
    GET: (id) => `${baseUrl}/product-reviews/${id}`,
    UPDATE: (id) => `${baseUrl}/product-reviews/${id}`,
    DELETE: (id) => `${baseUrl}/product-reviews/${id}`,
    GET_BY_PRODUCT: (productId) => `${baseUrl}/product-reviews/product/${productId}`,
    GET_BY_USER: (userId) => `${baseUrl}/product-reviews/user/${userId}`,
  },
  VENDOR_REVIEW_RESPONSES: {
    LIST: `${baseUrl}/vendor-review-responses`,
    CREATE: `${baseUrl}/vendor-review-responses`,
    GET: (id) => `${baseUrl}/vendor-review-responses/${id}`,
    UPDATE: (id) => `${baseUrl}/vendor-review-responses/${id}`,
    DELETE: (id) => `${baseUrl}/vendor-review-responses/${id}`,
    GET_BY_REVIEW: (reviewId) => `${baseUrl}/vendor-review-responses/review/${reviewId}`,
  },
  REVIEW_HELPFUL_VOTES: {
    LIST: `${baseUrl}/review-helpful-votes`,
    CREATE: `${baseUrl}/review-helpful-votes`,
    GET: (id) => `${baseUrl}/review-helpful-votes/${id}`,
    DELETE: (id) => `${baseUrl}/review-helpful-votes/${id}`,
    GET_BY_REVIEW: (reviewId) => `${baseUrl}/review-helpful-votes/review/${reviewId}`,
    GET_BY_USER: (userId) => `${baseUrl}/review-helpful-votes/user/${userId}`,
  },
  REVIEW_MEDIA_ASSETS: {
    LIST: `${baseUrl}/review-media-assets`,
    CREATE: `${baseUrl}/review-media-assets`,
    GET: (id) => `${baseUrl}/review-media-assets/${id}`,
    UPDATE: (id) => `${baseUrl}/review-media-assets/${id}`,
    DELETE: (id) => `${baseUrl}/review-media-assets/${id}`,
    GET_BY_REVIEW: (reviewId) => `${baseUrl}/review-media-assets/review/${reviewId}`,
  },
  CATEGORIES: {
    LIST: `${baseUrl}/categories`,
    CREATE: `${baseUrl}/categories`,
    GET: (id) => `${baseUrl}/categories/${id}`,
    UPDATE: (id) => `${baseUrl}/categories/${id}`,
    DELETE: (id) => `${baseUrl}/categories/${id}`,
    GET_PRODUCTS: (id) => `${baseUrl}/categories/${id}/products`,
    GET_CHILDREN: (id) => `${baseUrl}/categories/${id}/children`,
  },
  ADDRESSES: {
    LIST: `${baseUrl}/addresses`,
    CREATE: `${baseUrl}/addresses`,
    GET: (id) => `${baseUrl}/addresses/${id}`,
    UPDATE: (id) => `${baseUrl}/addresses/${id}`,
    DELETE: (id) => `${baseUrl}/addresses/${id}`,
    SET_DEFAULT: (id) => `${baseUrl}/addresses/${id}/set-default`,
    GET_DEFAULT: (type) => `${baseUrl}/addresses/default/${type}`,
  },
  COMPANIES: {
    LIST: `${baseUrl}/companies`,
    CREATE: `${baseUrl}/companies`,
    GET: (id) => `${baseUrl}/companies/${id}`,
    UPDATE: (id) => `${baseUrl}/companies/${id}`,
    DELETE: (id) => `${baseUrl}/companies/${id}`,
    GET_USERS: (id) => `${baseUrl}/companies/${id}/users`,
    ADD_USER: (id) => `${baseUrl}/companies/${id}/users`,
    REMOVE_USER: (id, userId) => `${baseUrl}/companies/${id}/users/${userId}`,
    GET_ADDRESSES: (id) => `${baseUrl}/companies/${id}/addresses`,
    GET_SHOPS: (id) => `${baseUrl}/companies/${id}/shops`,
    GET_ORDERS: (id) => `${baseUrl}/companies/${id}/orders`,
  },
  CONVERSATIONS: {
    LIST: `${baseUrl}/conversations`,
    CREATE: `${baseUrl}/conversations`,
    GET: (id) => `${baseUrl}/conversations/${id}`,
    UPDATE: (id) => `${baseUrl}/conversations/${id}`,
    DELETE: (id) => `${baseUrl}/conversations/${id}`,
    GET_PARTICIPANTS: (id) => `${baseUrl}/conversations/${id}/participants`,
    ADD_PARTICIPANT: (id) => `${baseUrl}/conversations/${id}/participants`,
    REMOVE_PARTICIPANT: (id, userId) => `${baseUrl}/conversations/${id}/participants/${userId}`,
    GET_MESSAGES: (id) => `${baseUrl}/conversations/${id}/messages`,
    ADD_MESSAGE: (id) => `${baseUrl}/conversations/${id}/messages`,
  },
  MESSAGES: {
    LIST: `${baseUrl}/messages`,
    CREATE: `${baseUrl}/messages`,
    GET: (id) => `${baseUrl}/messages/${id}`,
    UPDATE: (id) => `${baseUrl}/messages/${id}`,
    DELETE: (id) => `${baseUrl}/messages/${id}`,
    GET_BY_CONVERSATION: (conversationId) => `${baseUrl}/messages/conversation/${conversationId}`,
    GET_MEDIA: (id) => `${baseUrl}/messages/${id}/media`,
  },
  NOTIFICATIONS: {
    LIST: `${baseUrl}/notifications`,
    GET: (id) => `${baseUrl}/notifications/${id}`,
    MARK_READ: (id) => `${baseUrl}/notifications/${id}/read`,
    MARK_UNREAD: (id) => `${baseUrl}/notifications/${id}/unread`,
    GET_TARGETS: `${baseUrl}/notifications/targets`,
    GET_PREFERENCES: `${baseUrl}/notifications/preferences`,
    UPDATE_PREFERENCES: `${baseUrl}/notifications/preferences`,
  },
  SHIPMENTS: {
    LIST: `${baseUrl}/shipments`,
    CREATE: `${baseUrl}/shipments`,
    GET: (id) => `${baseUrl}/shipments/${id}`,
    UPDATE: (id) => `${baseUrl}/shipments/${id}`,
    DELETE: (id) => `${baseUrl}/shipments/${id}`,
    GET_ITEMS: (id) => `${baseUrl}/shipments/${id}/items`,
    GET_EVENTS: (id) => `${baseUrl}/shipments/${id}/events`,
    TRACK: (id) => `${baseUrl}/shipments/${id}/track`,
  },
  RETURNS: {
    LIST: `${baseUrl}/returns`,
    CREATE: `${baseUrl}/returns`,
    GET: (id) => `${baseUrl}/returns/${id}`,
    UPDATE: (id) => `${baseUrl}/returns/${id}`,
    DELETE: (id) => `${baseUrl}/returns/${id}`,
    GET_ITEMS: (id) => `${baseUrl}/returns/${id}/items`,
    APPROVE: (id) => `${baseUrl}/returns/${id}/approve`,
  },
  WISHLISTS: {
    LIST: `${baseUrl}/wishlists`,
    CREATE: `${baseUrl}/wishlists`,
    GET: (id) => `${baseUrl}/wishlists/${id}`,
    UPDATE: (id) => `${baseUrl}/wishlists/${id}`,
    DELETE: (id) => `${baseUrl}/wishlists/${id}`,
  },
  WISHLIST_ITEMS: {
    LIST: `${baseUrl}/wishlist-items`,
    CREATE: `${baseUrl}/wishlist-items`,
    GET: (wishlistId, productId) => `${baseUrl}/wishlist-items/${wishlistId}/${productId}`,
    DELETE: (wishlistId, productId) => `${baseUrl}/wishlist-items/${wishlistId}/${productId}`,
    GET_BY_WISHLIST: (wishlistId) => `${baseUrl}/wishlist-items/wishlist/${wishlistId}`,
  },
  SAVED_SEARCHES: {
    LIST: `${baseUrl}/saved-searches`,
    CREATE: `${baseUrl}/saved-searches`,
    GET: (id) => `${baseUrl}/saved-searches/${id}`,
    UPDATE: (id) => `${baseUrl}/saved-searches/${id}`,
    DELETE: (id) => `${baseUrl}/saved-searches/${id}`,
  },
  USER_FAVORITES: {
    LIST: `${baseUrl}/user-favorites`,
    CREATE: `${baseUrl}/user-favorites`,
    DELETE: (id) => `${baseUrl}/user-favorites/${id}`,
    GET_BY_USER: (userId) => `${baseUrl}/user-favorites/user/${userId}`,
    GET_BY_PRODUCT: (productId) => `${baseUrl}/user-favorites/product/${productId}`,
  },
  SEARCH_HISTORY: {
    LIST: `${baseUrl}/search-history`,
    GET: (id) => `${baseUrl}/search-history/${id}`,
    DELETE: (id) => `${baseUrl}/search-history/${id}`,
  },
};

